- gateway-customizations/customize-payment-gateway-labels.php
wasn't working until I did this on my test install
> Make it run later

- recurring-donations/move-recurring-checkbox-per-form.php
decided a separate snippet would be better, to limit confusion
> adds per-form recurring checkbox snippet

- translation-snippets/change-text.php
This first one is more of a sample. As more users have text to translate, I will add different specific snippets for that text.
> add local translation snippet

- gateway-customizations/customize-payment-gateway-labels.php
add correct value for Stripe's ACH ability via Plaid
> add correct value for Stripe's ACH ability via Plaid

- receipt-customizations/add-or-reorder-donation-receipt-items.php
This snippet is for adding or re-ordering items of donation receipt which has been extended relating to [PR #1724](https://github.com/WordImpress/Give/pull/1724) of Give Core
> Added Filter snippet for adding and reordering of donation receipt items

- translation-snippets/simple-translation-snippet.php
Added two more translation snippet. 
One for label "Donation Amount:" and another for "Choose Your Donation AMOUNT" for multi-level donation display type is dropdown.
> Added more translation snippet

- admin-functions/give-donation-submenu-show-all-status.php
Filter add to show display all the donation status 
The filter was introduces in version 1.8.12 of give PR https://github.com/WordImpress/Give/issues/1823
> Filter Add 

- admin-functions/change-donor-role.php
I have created this PR to fix the change in parameter of the filter hook. This is help to finalise the transaction properly without any notice or fatal error.
> MinorFix/Incorrect Parameter

- add-on-snippets/recurring-donations/manage-recurring-periods.php
This snippet will remove the Daily and Weekly option from the recurring periods.
> Added the snippet to manage recurring periods

- add-on-snippets/pdf-receipts/pdf-receipt-custom-font.php
- add-on-snippets/recurring-donations/give-is-recurring-email-tag.php
- admin-functions/display-current-url-donation-details
- form-customizations/display-accepted-cards.php
- form-customizations/give-simple-ticket-incrementer.php
- form-customizations/mailing-address-custom-fields.php
- useful-queries/better-donor-list-shortcode.php
- useful-queries/sample-transaction-queries.php
Pass all variables through a WordPress escaping function before echoing
it. When it's a large chunk of data, pass the entire output through
`wp_kses_post()` for an extra level of sanity.
> Escape output before printing to DOM

- form-customizations/custom-fields-plugin.php
This PR will upgrade email tag code to Give 2.0
For Ref: https://github.com/WordImpress/Give-Docs/issues/131#issuecomment-359055562
> [Code Improvement] Email tags 

- add-on-snippets/pdf-receipts/min-amount-for-pdf-receipt.php
- email-customization/conditional-email-based-on-amount.php
This PR resolves #52 
I've replaced the deprecated functions with the correct one's to make it work properly and made some formatting changes.
> refactor(deprecated-fns): replaced deprecated fns with correct ones

- useful-queries/recent-donors-shortcode.php
This PR resolves #50 
I've tested it manually and optimised code. Also, kept the functioning as it is for now.
> refactor(shortcode): Use new Give_Donor class in snippets

- useful-queries/list-donation-forms-plus-goals.php
- useful-queries/recent-donors-shortcode.php
- useful-queries/sample-transaction-queries.php
> refactor(templates): Refactor useful-queries templates

- email-customization/disable-donor-notification.php
> fix(template): Remove deprecated functions #53

- gateway-customizations/authorizenet-phonenumber-from-custom-field.php
this lets you create a custom phone field on a donation form and pass that phone number to Authorize.net.
> added authorizenet-phonenumber-from-custom-field.php

- form-customizations/custom-per-form-currency.php
> fix(doc): improvement of per form currency snippet.

- form-customizations/custom-fields-plugin.php
PR to fix #73 
Tested by adding custom meta column with some value and without some value
New feature (non-breaking change which adds functionality)
> fix(snippet): update custom field snippet #73

- donor/add-donor-meta.php
This PR is to support Give Core PR https://github.com/impress-org/give/pull/3732
I've tested this PR by adding the snippet and then processing donation with custom field "Phone Number" and then exporting the data of the successful donation.
New feature (a non-breaking change which adds functionality)
> feat: include custom columns in donor export CSV #3709

- form-customizations/give-simple-ticket-incrementer.php
This PR resolve #85 
I've tested it based on the "How to use" comment in the snippet. So, we're not supporting Currency Switcher in this issue.
> feat: make incrementer plugin work when multiple forms are on a page #85

- form-customizations/give-simple-ticket-incrementer.php
Resolves #108 and #102  
- Allows for multi-level form support
- Improves code so it's dryer and uses triggers from core
- Allows for various currency formatting
- Improves ticket input by having a `max` and `min`
- Allows to change gateways without losing total donation amount
A lot more can be done here but this is a decent improvement.
> refactor: improve basic ticketing support plugin snippet

- gateway-customizations/add-custom-field-to-braintree-payment.php
This PR will resolve https://github.com/impress-org/give-braintree/issues/43
> fix: send Form Title To Braintree

- form-customizations/css-customizations/multi-step-inline-styles.php
Removing the inline comment and changing to block comment, because when the style is inlined, it comments all the styles and it ends up not working.
If someone uses this script and doesn't remove the inline comment, went hey apply the styles, the inline comment will make everything a comment and it will not work.
> block comment

- translation-snippets/advanced-translation-snippet.php
The recurring period parameter needs to be added to the Make this donation text
Adds the recurring period parameter to this script, so it works properly.
> Adds parameters to make this donation

- custom-shortcodes/donations-for-a-form-shortcode.php
Creates a shortcode to display a message with the total number of donations for a specific donation form.
> Shortcode: add example give_raised_for_forms

- admin-functions/add-table-list-column.php
This PR includes a simplified snippet that helps developers to add new columns to our new List Tables.
> doc: add snippet that adds custom columns to the new list tables

- add-on-snippets/fee-recovery/check-optin-automatically.php
- gateway-customizations/add-custom-gateways.php
.click() updates the Donation Summary where .prop('checked', true) did not.
> Changed: click() updates the donation summary

- add-on-snippets/authorize/authorizenet-description-filter.php
- translation-snippets/givewp-weblog-integration
Added snippet to filter the payment description sent to Authorize.net
> Authorize.net payment description filter

- form-customizations/css-customizations/enqueue-style-for-givewp-iframes.php
- translation-snippets/givewp-weblog-integration
- translation-snippets/givewp-weblog-integration.php
The filter to add custom iframe styles to the Donor Dashboard was outdated. I also added the filter for the Classic template in the code comment.
> Changed: Donor Dashboard filter for custom CSS
